name: Nix actions

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build Package
      run: nix build .\#rucli
